import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';

export default function Home() {

  useEffect(() => {
      async function fetchAPI() {
        const url = `${process.env.NEXT_PUBLIC_URL}?access_token=${process.env.NEXT_PUBLIC_ACCESS_TOKEN}`;
        const response = await fetch(url);
        const data = await response.json();
        console.log(data);
      }
      fetchAPI();
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Strava API App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Strava Accountability App</h1>

        <p className={styles.description}>Every mile I run, or day I lift, I will reward myself in some way.</p>
        <p className={styles.description}>A potential idea is doing the GitHub progress bar but for Strava. Another idea
        would include paying myself in Ethereum or something.</p>
      </main>
    </div>
  )
}
